version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    volumes:
      - frontend_data:/app/frontend/build

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  frontend_data:
  backend_data:
